source 'http://rubygems.org'

gem 'rails', '3.1.0.rc4'
gem "mongoid", '2.0.2'
gem "bson_ext", "~> 1.3"
gem 'factory_girl', '2.0.0.beta2'
gem 'factory_girl_rails', '1.1.beta1'
gem 'rspec-rails'
gem 'rspec'
gem 'remarkable_mongoid'
gem 'database_cleaner'
gem 'jquery-rails'
gem 'stringex'
gem 'carrierwave'
gem 'cloudfiles'
gem 'maruku'
gem 'capistrano'